kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - cs.restricted
    verbs:
      - use