kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted
subjects:
  - kind: Group
    name: system:serviceaccounts # all service accounts
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: system:authenticated # all authenticated users
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: system:unauthenticated # all unauthenticated users
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: restricted # A references to the role above
  apiGroup: rbac.authorization.k8s.io